export { default as UserTable } from "./UserTable"
export { default as UserDetail } from "./UserDetail"
export { default as ProductTable } from "./ProductTable"
export { default as ProductForm } from "./ProductForm"
export { default as PromotionTable } from "./PromotionTable"
export { default as PromotionForm } from "./PromotionForm"
