"""added role to users

Revision ID: 6083af4b1847
Revises: 7400e65611f6
Create Date: 2026-01-14 23:47:36.375232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6083af4b1847'
down_revision = '7400e65611f6'
branch_labels = None
depends_on = None


def upgrade():
    # 1) Add column as nullable first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # 2) Set default role for existing users
    op.execute("UPDATE users SET role = 'customer' WHERE role IS NULL")

    # 3) Alter column to NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
