"""add product admin fields

Revision ID: 7d6e84d6b10b
Revises: 827ff45d0ee0
Create Date: 2026-01-20 17:12:07.314834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6e84d6b10b'
down_revision = '827ff45d0ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('original_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reviews', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('reviews')
        batch_op.drop_column('rating')
        batch_op.drop_column('icon')
        batch_op.drop_column('discount')
        batch_op.drop_column('original_price')
        batch_op.drop_column('unit')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
