"""add invoice delivery fields

Revision ID: 9ad0056ee9e1
Revises: 02f63df49bc5
Create Date: 2026-01-20 20:21:51.336700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad0056ee9e1'
down_revision = '02f63df49bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_full_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('delivery_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('delivery_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_apartment', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('delivery_notes')
        batch_op.drop_column('delivery_zip_code')
        batch_op.drop_column('delivery_state')
        batch_op.drop_column('delivery_city')
        batch_op.drop_column('delivery_apartment')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('delivery_phone')
        batch_op.drop_column('delivery_email')
        batch_op.drop_column('delivery_full_name')

    # ### end Alembic commands ###
